version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]